### ISSUE TITLE
Problem with cartesio space contol example

### ISSUE THREAD

**Issue by gabri-v** [ADVRHumanoids/pino_fhi#1]
I have some problem with Cartesian space control example.

These are all steps that I've taken:

I had previously created the robot model

In the pino-embedded I started the EtherCat master:
`ecat_master`

In a new terminal, also in pino-embedded, I started the xbot2 with the robot in impedance mode
`xbot2-core --hw ec_imp`

In a new terminal , also in pino-embedded, I launched the launch file
`mon launch ModularBot ModularBot_ik.launch`

In a new terminal on the pilot PC I sourced the ws:
`source src/fhi_ws/devel_setup.bash`

and than I ran rviz:
`rviz`

In the rviz window I clicked on Add and than I added RobotModel
In Global Option I changed the Fixed Frame -> ci/base_link
In the RobotModel I set the TF Prefix -> ci
At this point I see the model in RViz.
I clicked on Add and than I added InteractiveMarkers
In the InteractiveMarkers I set the Update Topic -> /L_4_A_cartesian_marker_server/update
It is the only topic that appears.
At this point the interactive marker appear attach to the last joint of the robot.
If I try to move it only the last joint (of different color) moves, the whole robot remains stationary, both in RViz and in reality.
I attach an image from RViz:
![Screenshot from 2022-05-06 15-46-23](https://user-images.githubusercontent.com/105058941/167146454-3e844a98-dcfd-4edb-bc35-3b474ad28194.png)

I tried looking at the topics:
the update is done on the topic / L_4_A_cartesian_marker_server / update which however does not contain information:
```
lab@lab-System-Product-Name:~$ rostopic echo /L_4_A_cartesian_marker_server/update
server_id: "/interactive_markers"
seq_num: 5
type: 0
markers: []
poses: []
erases: []
```

It also appears that the node /ros_server_node receives information from another topic: /cartesio/changed_controller_event, the latter does not publish anything.

In this situation, whatever I do, the topic /xbotcore/command sends the current position data which I assume is from the topic /xbotcore/joint_states.
I attach two images of Node Graph
![Screenshot from 2022-05-06 15-53-22](https://user-images.githubusercontent.com/105058941/167147124-f96216f8-c8a9-4b90-af01-359b9e7a5bfc.png)
![Screenshot from 2022-05-06 15-54-10](https://user-images.githubusercontent.com/105058941/167147133-2349b5a9-e53c-4359-9277-6f04c89d8405.png)

**Comment by liesrock** [comment]
Thanks @gabri-v : did you try to enable the continuous control clicking with the right button of the mouse and selecting the proper box?
If this is not documented we will update the documentation.

**Comment by gabri-v** [comment]
Thanks @liesrock if I enable the continuous control it's work. I'm not sure this step is documented.
Thanks to the availability.
